name: Check for New Launch
run-name: Check for New Launch
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:
jobs:
  update_tle_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
    - name: Check for new launch and update TLE data
      id: check_new_launch
      run: |
        node check-new-launch.js | tee /tmp/output.txt
        if grep -q "Added new launch" /tmp/output.txt; then
          echo "new_launch=true" >> $GITHUB_OUTPUT
        else
          echo "new_launch=false" >> $GITHUB_OUTPUT
        fi
    - name: Configure Git
      if: steps.check_new_launch.outputs.new_launch == 'true'
      run: |
        git config --local user.email "findstarlink-data[bot]@users.noreply.github.com"
        git config --local user.name "findstarlink-data[bot]"
    - name: Commit changes
      if: steps.check_new_launch.outputs.new_launch == 'true'
      run: |
        echo "RELEASE: $(cat /tmp/output.txt)" > /tmp/commit_msg.txt

        git add -A
        git commit -F /tmp/commit_msg.txt || echo "No changes to commit"
    - name: Push changes
      if: steps.check_new_launch.outputs.new_launch == 'true'
      run: git push
