# Generated initially using github-actions-wizard (https://github.com/cmdr2/github-actions-wizard)

name: Deploy Data
run-name: Deploy Data
on:
  push:
    branches:
    - main
jobs:
  deploy_to_cloudflare_pages_on_main_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create tle.js
      run: |-
        echo "var TLE = " > tle.js
        cat tle.json >> tle.js
        echo "\n" >> tle.js
    - name: Copy files into the build
      run: |-
        mkdir build
        cp tle.json tle.js strings_en-US.json starlink_celestrak_supplemental.txt build/
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy build --project-name=findstarlink-data
    - name: Check if commit message has "RELEASE:" in it
      id: check_release
      run: |
        if git log -1 --pretty=%B | grep -q "RELEASE:"; then
          echo "is_release=true" >> $GITHUB_OUTPUT
        else
          echo "is_release=false" >> $GITHUB_OUTPUT
        fi

        # create a version based on current date and time
        VERSION=$(date +'%Y.%m.%d.%H%M')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Create a release if necessary
      if: steps.check_release.outputs.is_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.check_release.outputs.version }}
        name: v${{ steps.check_release.outputs.version }}
        body: |
          ${{ env.COMMIT_MSG }}
